### ISSUE TITLE
Koodin katselmointi

### ISSUE THREAD

**Issue by RoniNiklas** [Siipis/ot-harjoitustyo#1]
Ladattu 8.12.19. klo 18.

Yleisiä kommentteja käytöstä:
- Jännä ohjelma. Toimii lähes virheettömästi ja kuvauksen mukaisesti mitä ehdin testailla.
- Käyttöliittymä selkeä. Ohjelma toimii nopeasti.
- Tietokanta toimii.
- .jar paketti toimii.

Pakkausrakenne:

- Pakkausrakenne hyvä. Ohjelman eri osat jaettu selkeästi erilleen omille vastuualueilleen.

Koodin laatu:

- Erittäin laadukasta ja selkeää koodia.
- Metodit lyhyitä ja selkeästi nimettyjä. Yhden vastuun periaate käytössä.
- Muuttujat selkeästi nimettyjä.

Dokumentointi:

- Projekti on kattavasti dokumentoitu. Selkeät käyttöohjeet.

Kehitysehdotuksia:

Pieni bugi/epäselvyys käytössä. Jos antaa virheellisen luvun min. lengthiksi tai max. lengthiksi, niin käyttöliittymään jää virheellinen luku näkyviin, kun ohjelma taas resetoi luvun johonkin toiseen arvoon. 

Esimerkki: 

- Alkutilanteessa min length ja max length ovat molemmat 5.
- Muutan min. lengthin kokoon 10 käyttöliittymässä. Min. length on nyt liian iso, joten ohjelma ei aseta sitä arvoon 10 vaan antaa virheviestin.
- Muutan max. lengthin kokoon 10. 
- Luon nimen. 
- Ohjelma luo nyt nimen min. lengthillä 1, sillä language-luokan setMinLength metodi resetoi arvon, sillä se oli asetettaessa liian iso.
- Käyttöliittymässä näkyy kumminkin vielä virheellinen min length arvo 10.

Tämä sama virhe toimii myös toisinpäin, jos asettaa virheellisen max.length arvon.

Ohjelmaan voisi lisätä koodinpätkän, joka estää käyttöliittymää muokkaamasta arvoa virheelliseksi. Alla ehdotus vastaavan toiminnon lisäämisesta LengthSelectionController -luokan makeListener metodiin, joskin tässä on omat ongelmansa (jos syöttää virheellisen luvun, niin joutuu syöttämään eri toimivan luvun kuin mitä aiemmin käytti, jotta generate nappula palaa toimintaan.). Keksit mahdollisesti itse parempiakin tapoja estää kyseisen virheellisen käytön aiheuttamia epäselvyyksiä.

```
private ChangeListener<String> makeListener(NumericField field) {
        return (o, oldValue, newValue) -> {
            this.hideError();

            try {
                if (field == minLength) {
                    currentLanguage.setMinLength(minLength.value());
                }

                if (field == maxLength) {
                    currentLanguage.setMaxLength(maxLength.value());
                }
            } catch (IntegerOutOfBoundsException e) {
                if (field == minLength) {
                    this.minLength.setText(oldValue);
                } else {
                    this.maxLength.setText(oldValue);
                }
                this.showError(e.getMessage());
            }
        };
    }
```

Toinen korjaava palaute on, että koodissa on joitain turhia kommentteja metodien yläpuolella. Koodi monessa paikkaa hyvin selkeää itsessään, ja ei tarvitse näitä erillisiä kommentteja. Esim. childcontrollerissa on seuraavanlainen turha kommentti. Samanlaisia myös muualla: 

```
 /**
     * Sets the error status.
     *
     * @param hasError error status
     */
    protected void setError(boolean hasError) {
        this.hasError = hasError;

        this.parent.renderChildren();
   }
```
Tietenkin on hyvä pitää mielessä, että koodin lukija varmasti tajuaa sen toimintaa, mutta näin selkeästi kirjoitettuja toimintoja ei välttämättä täydy erikseen kommentoida.

Hyvää työtä.

**Comment by Siipis** [comment]
Kiitos paljon palautteesta! Pitääpä miettiä, miten käsittelen tuon löytämäsi virheen. Käynpä samalla muuttamassa tuota mainitsemaasi kommenttia, ettei se olisi aivan noin tautologinen :D
